# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointCadastre
                                 A QGIS plugin
 essai_description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-29
        copyright            : (C) 2021 by eric narro
        email                : eric.narro.ied@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PointCadastre class from file PointCadastre.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .point_cadastre import PointCadastre
    return PointCadastre(iface)
